web:
  gateway:
    protected_access: false
  eshop_url: 'https://obchod.altar.cz/draci-doupe-a-jine-rpg-hry-draci-doupe-plus-c-1_7.html'
  name: 'O Norikovi'
  title_smiley: ''
  menu:
    position_fixed: false
    show_home_button_on_homepage: true
    show_home_button_on_routes: false
    home_button_target: 'https://www.drdplus.info'
google:
  analytics_id: 'UA-121206931-0'
application:
  yaml_file_with_routes: 'routes.yml'