web:
  gateway:
    protected_access: false
  eshop_url: 'https://obchod.altar.cz/draci-doupe-a-jine-rpg-hry-draci-doupe-plus-c-1_7.html'
  name: 'O Norikovi'
  title_smiley: ''
  menu:
    position_fixed: false
    home_button:
      show_on_gateway: true
      show_on_homepage: false
      show_on_routes: false
      target: 'https://www.drdplus.info'
google:
  analytics_id: 'UA-121206931-22'
application:
  yaml_file_with_routes: 'routes.yml'